version: '3.8'

services:
  fe-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      - "9090:9090"  # Métricas
    environment:
      - NODE_ENV=development
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://fe_manager:password@postgres:5432/fe_manager
      - CHROMA_URL=http://chromadb:8000
      - LOG_LEVEL=info
      - OTEL_ENABLED=true
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - redis
      - postgres
      - chromadb
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
      - ./plugins:/app/plugins
    networks:
      - fe-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - fe-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fe_manager
      - POSTGRES_USER=fe_manager
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - fe-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fe_manager"]
      interval: 30s
      timeout: 5s
      retries: 3

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    volumes:
      - chromadb-data:/chroma/chroma
    networks:
      - fe-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Servicios de monitoreo (opcionales)
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - fe-manager-network
    restart: unless-stopped

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - fe-manager-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  chromadb-data:
    driver: local

networks:
  fe-manager-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16